language: java
install: true

stages:
- name: build
- name: snapshot
  if: branch = development
- name: release
  if: branch = master

jobs:
  include:
  - stage: build
    script: ./gradlew build
  - stage: snapshot
    script: ./gradlew artifactoryPublish --exclude-task test -Dsnapshot=true -Dbintray.user=${BINTRAY_USER} -Dbintray.key=${BINTRAY_KEY} -Dbuild.number=${TRAVIS_BUILD_NUMBER}
  - stage: release
    script: ./gradlew bintrayUpload --exclude-task test -Dbintray.user=${BINTRAY_USER} -Dbintray.key=${BINTRAY_KEY} -Dbuild.number=${TRAVIS_BUILD_NUMBER}

deploy:
  provider: releases
  api_key: ${ACCESS_TOKEN}
  skip_cleanup: true
  file: build/libs/dxmem-${TRAVIS_TAG}.jar
  on:
    repo: hhu-bsinfo/dxmem
    branch: master
    tags: true
